"""add created_at field

Revision ID: 3fa5f3a022a6
Revises: a22bf4cc1fe6
Create Date: 2025-11-30 21:29:52.807996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa5f3a022a6'
down_revision = 'a22bf4cc1fe6'
branch_labels = None
depends_on = None


def upgrade():
    # ...
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.func.now(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
