"""Initial migration

Revision ID: 690bc92dc42b
Revises: ded155777ca8
Create Date: 2025-11-30 20:41:56.197498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690bc92dc42b'
down_revision = 'ded155777ca8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
